-- Demo Websites: a second major module, and the per-account switch for it.
--
-- Nothing here touches `leads`, `meeting_recordings`, `lead_activities` or any
-- other existing table except `users`, and the change to `users` is two new
-- columns with defaults. No existing row is rewritten, no id changes, and no
-- lead is copied anywhere: `demo_websites` starts empty and is filled only by
-- `POST /api/demo-websites`.
--
-- ---------------------------------------------------------------------------
-- The two defaults, which are the safety argument
-- ---------------------------------------------------------------------------
-- `can_access_leads` defaults to TRUE and `can_access_demo_websites` to FALSE,
-- so every account that already exists keeps exactly the access it has today
-- and gains nothing. An agent who was working the worklist this morning is
-- still working it after this migration; nobody is silently given a module an
-- administrator never granted them.
--
-- Administrators are unaffected in a stronger sense: their flags are written
-- like everyone else's but are never read, because `ADMIN_MODULE_ACCESS` in
-- `lib/modules.ts` answers "yes" for both modules before the columns are
-- consulted. So an administrator cannot be locked out of a module by a stray
-- UPDATE against this table.
--
-- ---------------------------------------------------------------------------
-- The image columns
-- ---------------------------------------------------------------------------
-- Six nullable columns on `demo_websites` rather than a table of their own: a
-- demo website has at most one image, they are written and cleared as a set,
-- and a one-to-one relation would only be a join to reach them.
-- `image_storage_key` is UNIQUE so two rows can never claim the same object on
-- disk, which is what makes "delete the row, then delete its file" safe to run
-- without wondering whether somebody else still needs the bytes.
--
-- The key is a path *within* the demo image store (`DEMO_IMAGES_DIR`, outside
-- the release tree and outside `public/`). It is generated by the server and
-- never accepted from a client.

-- CreateEnum
CREATE TYPE "demo_website_status" AS ENUM ('draft', 'active', 'presented', 'archived');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "can_access_demo_websites" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "can_access_leads" BOOLEAN NOT NULL DEFAULT true;

-- CreateTable
CREATE TABLE "demo_websites" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "client_name" TEXT NOT NULL DEFAULT '',
    "demo_url" TEXT NOT NULL,
    "phone" TEXT,
    "email" TEXT,
    "status" "demo_website_status" NOT NULL DEFAULT 'active',
    "notes" TEXT NOT NULL DEFAULT '',
    "image_storage_key" TEXT,
    "image_format" TEXT,
    "image_width" INTEGER,
    "image_height" INTEGER,
    "image_file_size" INTEGER,
    "image_updated_at" TIMESTAMP(3),
    "created_by_user_id" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "demo_websites_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "demo_websites_image_storage_key_key" ON "demo_websites"("image_storage_key");

-- CreateIndex
CREATE INDEX "demo_websites_created_at_idx" ON "demo_websites"("created_at");

-- CreateIndex
CREATE INDEX "demo_websites_status_idx" ON "demo_websites"("status");

-- AddForeignKey
ALTER TABLE "demo_websites" ADD CONSTRAINT "demo_websites_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
