#!/usr/bin/env bash
#
# Lead Portal — roll back to the previous colour slot.
#
#   bash /var/www/lead-portal/repo/deploy/rollback.sh
#
# deploy.sh never deletes the release it replaced: it is still sitting in the
# other slot directory, already built. Rolling back is therefore the same flip
# in reverse — start it, health-check it, repoint nginx — and takes seconds
# rather than a rebuild.
#
# What this does NOT do is roll back the database. If the deploy you are undoing
# applied a migration, reverting the code can leave it reading a schema it does
# not expect. Check `npx prisma migrate status` before assuming a rollback is
# clean; a forward fix is usually safer than a schema revert.

set -euo pipefail

APP_NAME="lead-portal"
APP_ROOT="/var/www/${APP_NAME}"
UPSTREAM_FILE="/etc/nginx/conf.d/${APP_NAME}-upstream.conf"

declare -A SLOT_PORT=( [blue]=3001 [green]=3002 )

log()  { printf '\n\033[1;32m==>\033[0m %s\n' "$*"; }
die()  { printf '\n\033[1;31m[fail]\033[0m %s\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root."

if grep -q '3002' "$UPSTREAM_FILE" 2>/dev/null; then
  LIVE=green; TARGET=blue
else
  LIVE=blue;  TARGET=green
fi
TARGET_PORT="${SLOT_PORT[$TARGET]}"

[[ -f "${APP_ROOT}/${TARGET}/server.js" ]] \
  || die "No previous release in ${APP_ROOT}/${TARGET}. Nothing to roll back to."

PREV_SHA="$(cat "${APP_ROOT}/${TARGET}/RELEASE_SHA" 2>/dev/null || echo unknown)"
log "Rolling back from ${LIVE} to ${TARGET} (${PREV_SHA}) on port ${TARGET_PORT}"

systemctl restart "lead-portal@${TARGET}"

for _ in $(seq 1 30); do
  curl -fsS --max-time 3 "http://127.0.0.1:${TARGET_PORT}/api/health" 2>/dev/null \
    | grep -q '"status":"ok"' && { HEALTHY=true; break; }
  sleep 1
done
[[ "${HEALTHY:-false}" == true ]] || {
  journalctl -u "lead-portal@${TARGET}" -n 40 --no-pager || true
  systemctl stop "lead-portal@${TARGET}" || true
  die "Previous release will not start either. Traffic left on ${LIVE}."
}

cat > "$UPSTREAM_FILE" <<EOF
# Generated by deploy/rollback.sh — do not edit by hand.
# Live slot: ${TARGET}    Release: ${PREV_SHA}
upstream lead_portal {
    server 127.0.0.1:${TARGET_PORT};
    keepalive 32;
}
EOF

nginx -t || die "nginx rejected the generated upstream; traffic unchanged."
systemctl reload nginx
systemctl stop "lead-portal@${LIVE}" || true

log "Rolled back to ${TARGET} (${PREV_SHA})."
