/**
 * What counts as an activity interval: the limits, the formula, and the
 * validation that enforces both.
 *
 * The same split `lib/screenshotRules.ts` keeps from `lib/screenshots.ts`, and
 * `lib/performanceRules.ts` from `lib/performance.ts`: nothing here touches the
 * database, the filesystem or `next/headers`, so the shapes and the arithmetic
 * can be imported by a route handler, a server page and a client component
 * alike. Everything below is pure — input in, a value or a typed error out.
 */

import { addDays, resolveRange, type DateRange } from "./performanceRules";

/** An expected refusal, carrying the status the route should answer with. */
export class ActivityError extends Error {
  constructor(
    readonly code: string,
    message: string,
    readonly status: number,
  ) {
    super(message);
  }
}

/**
 * The shortest interval worth a row.
 *
 * Below this the percentage is dominated by its own rounding — three events in
 * two seconds reads as 100% activity and means nothing — and a client
 * submitting one-second intervals would write sixty rows a minute per agent for
 * no extra information.
 */
export const MIN_INTERVAL_SECONDS = 10;

/**
 * How much longer than the configured cadence an interval may be.
 *
 * Twice, so a workstation whose timer slipped or which merged two windows after
 * a hiccup is still accepted, while a client claiming a single eight-hour
 * "interval" is not. The multiplier is here rather than as a constant of its own
 * because it is only ever meaningful against the configured interval.
 */
const MAX_INTERVAL_MULTIPLE = 2;

/**
 * How far an interval's timestamps may sit from the server's clock.
 *
 * Tighter than the screenshot tolerance (six hours), and refused rather than
 * clamped. The reason is the difference between the two artefacts: a screenshot
 * with a wrong `capturedAt` is still a real photograph of a real screen and is
 * worth keeping with a corrected timestamp, whereas an activity interval *is*
 * its timestamps — clamping them would invent a window nobody observed and add
 * it to somebody's active time.
 *
 * Fifteen minutes covers a delayed submission after a network failure, which is
 * the case the Monitor actually has, and the bounded local buffer it is allowed
 * to keep is one interval deep.
 */
export const CLOCK_SKEW_TOLERANCE_MS = 15 * 60 * 1000;

/**
 * The ceiling on a single interval's event count.
 *
 * A generous multiple of any human rate: at the default calibration of 120
 * events a minute this is roughly eighty times "fully active", so it refuses a
 * client sending a fabricated number without ever refusing a real fast typist.
 * Applied per interval-second so the bound scales with a longer window rather
 * than becoming meaningless on one.
 */
export const MAX_EVENTS_PER_SECOND = 160;

/** The idempotency key's shape. Generated by the client; never trusted for more. */
const CLIENT_KEY_PATTERN = /^[A-Za-z0-9._:-]{8,120}$/;

/**
 * The activity percentage, and the whole of what it means.
 *
 * ---------------------------------------------------------------------------
 * The formula
 * ---------------------------------------------------------------------------
 *
 *     observed  = keyboardActivityCount + mouseActivityCount
 *     expected  = expectedEventsPerMinute × (durationSeconds ÷ 60)
 *     percentage = round(min(100, observed ÷ expected × 100))
 *
 * That is all of it. It is deliberately simple, deliberately predictable, and
 * deliberately documented in three places (here, `.env.example`, the README) so
 * that nobody has to reverse-engineer it from a dashboard.
 *
 * ---------------------------------------------------------------------------
 * What it is not
 * ---------------------------------------------------------------------------
 * **It is not productivity.** It counts keyboard and mouse events and nothing
 * else. An agent on a fifteen-minute call that ends in a booked meeting scores
 * close to zero on it, and that is not the metric being wrong — it is the metric
 * measuring what it measures. Every screen that shows this figure says so in
 * words next to it, and none of them ranks agents by it.
 *
 * **It is not the client's number.** The desktop client may send an
 * `activityPercentage` and it is discarded: this function is called with the
 * counts and the server's own configured rate, and the result is what is
 * stored. A workstation therefore cannot report itself as busy, only as having
 * had events — and those are bounded by {@link MAX_EVENTS_PER_SECOND}.
 *
 * Clamped at 100 rather than allowed to run over: "180% active" is not a thing
 * anybody can act on, and the excess says only that the calibration is low for
 * this person's input style.
 */
export function activityPercentage(
  keyboardActivityCount: number,
  mouseActivityCount: number,
  durationSeconds: number,
  expectedEventsPerMinute: number,
): number {
  if (durationSeconds <= 0 || expectedEventsPerMinute <= 0) return 0;

  const observed = keyboardActivityCount + mouseActivityCount;
  const expected = expectedEventsPerMinute * (durationSeconds / 60);

  return Math.max(0, Math.min(100, Math.round((observed / expected) * 100)));
}

/**
 * What the Monitor sends. Every field is advisory except the counts and the
 * key, and even those are bounded — see {@link validateActivitySubmission}.
 *
 * Note what is *absent* and cannot be added by a client: there is no `userId`,
 * no `agentId` and no `workSessionId` in this shape. The route derives all
 * three from the authenticated device and the portal's own view of the shift,
 * so a body carrying them has nowhere to put them. That is stronger than
 * ignoring them, because there is no field to forget to ignore.
 */
export interface ActivitySubmission {
  startedAt: Date;
  endedAt: Date;
  durationSeconds: number;
  keyboardActivityCount: number;
  mouseActivityCount: number;
  clientKey: string;
}

/** The bounds a submission is checked against, resolved from server config. */
export interface ActivityBounds {
  /** `activityIntervalSeconds()` — the configured cadence. */
  intervalSeconds: number;
  /** The server's clock at the moment of the request. */
  now: Date;
  /** When the resolved work session began. An interval cannot predate its shift. */
  sessionStartedAt: Date;
}

/** A whole, finite, non-negative number, or null. */
function count(raw: unknown): number | null {
  const value = typeof raw === "number" ? raw : Number(raw);
  if (!Number.isFinite(value) || !Number.isInteger(value) || value < 0) return null;
  return value;
}

/** A parseable instant, or null. */
function instant(raw: unknown): Date | null {
  if (typeof raw !== "string" && !(raw instanceof Date)) return null;
  const parsed = raw instanceof Date ? raw : new Date(raw);
  return Number.isNaN(parsed.getTime()) ? null : parsed;
}

/**
 * Turn an untrusted body into a submission, or refuse it.
 *
 * Refuses rather than clamps, unlike `resolveScreenshotQuery` and
 * `resolveCapturedAt`. Those two are reading a *filter* and a *label*, where a
 * bad value costs an empty screen or a corrected timestamp. This is reading
 * something that will be added to a person's recorded active time, so a value
 * that cannot be believed must not become a row — a silently clamped interval is
 * indistinguishable in the database from an observed one.
 *
 * The order is cheapest-first and most-specific-message-first, so a client
 * debugging its integration gets the one refusal that names its actual mistake.
 */
export function validateActivitySubmission(
  body: unknown,
  bounds: ActivityBounds,
): ActivitySubmission {
  if (typeof body !== "object" || body === null) {
    throw new ActivityError("invalid_body", "Request body must be a JSON object.", 400);
  }

  const payload = body as Record<string, unknown>;

  // --- the idempotency key ------------------------------------------------
  const clientKey = typeof payload.clientKey === "string" ? payload.clientKey.trim() : "";
  if (!CLIENT_KEY_PATTERN.test(clientKey)) {
    throw new ActivityError(
      "invalid_client_key",
      "clientKey must be 8–120 characters of A–Z, a–z, 0–9, dot, underscore, colon or hyphen.",
      400,
    );
  }

  // --- the window ---------------------------------------------------------
  const startedAt = instant(payload.startedAt);
  const endedAt = instant(payload.endedAt);
  if (!startedAt || !endedAt) {
    throw new ActivityError(
      "invalid_timestamps",
      "startedAt and endedAt must both be ISO 8601 instants.",
      400,
    );
  }

  if (endedAt <= startedAt) {
    throw new ActivityError(
      "invalid_timestamps",
      "endedAt must be after startedAt.",
      422,
    );
  }

  const durationSeconds = Math.round((endedAt.getTime() - startedAt.getTime()) / 1000);
  const maxSeconds = bounds.intervalSeconds * MAX_INTERVAL_MULTIPLE;

  if (durationSeconds < MIN_INTERVAL_SECONDS || durationSeconds > maxSeconds) {
    throw new ActivityError(
      "invalid_duration",
      `An activity interval must be between ${MIN_INTERVAL_SECONDS} and ${maxSeconds} seconds long (got ${durationSeconds}).`,
      422,
    );
  }

  // --- against the server's clock ----------------------------------------
  // The future bound is tight on purpose: a client may legitimately submit a
  // window that ended a few minutes ago (a retry), but nothing legitimate
  // reports a window that has not finished happening.
  if (endedAt.getTime() > bounds.now.getTime() + CLOCK_SKEW_TOLERANCE_MS) {
    throw new ActivityError(
      "timestamp_in_future",
      "That interval ends in the future. Check the workstation's clock.",
      422,
    );
  }

  if (startedAt.getTime() < bounds.now.getTime() - CLOCK_SKEW_TOLERANCE_MS) {
    throw new ActivityError(
      "timestamp_too_old",
      "That interval is too old to accept. Activity is reported as it happens.",
      422,
    );
  }

  // --- against the shift it claims to be inside ---------------------------
  // The work session is the authority on when work happened, so an interval
  // that starts before its shift did is refused rather than trimmed. Trimming
  // would be the server inventing a window, which is the one thing this whole
  // module exists to prevent.
  if (startedAt < bounds.sessionStartedAt) {
    throw new ActivityError(
      "outside_work_session",
      "That interval starts before the current work session did.",
      422,
    );
  }

  // --- the counts ---------------------------------------------------------
  const keyboardActivityCount = count(payload.keyboardActivityCount);
  const mouseActivityCount = count(payload.mouseActivityCount);

  if (keyboardActivityCount === null || mouseActivityCount === null) {
    throw new ActivityError(
      "invalid_counts",
      "keyboardActivityCount and mouseActivityCount must be whole numbers of zero or more.",
      400,
    );
  }

  const ceiling = MAX_EVENTS_PER_SECOND * durationSeconds;
  if (keyboardActivityCount > ceiling || mouseActivityCount > ceiling) {
    throw new ActivityError(
      "implausible_counts",
      `An interval of ${durationSeconds}s cannot hold more than ${ceiling} events of either kind.`,
      422,
    );
  }

  return {
    startedAt,
    endedAt,
    durationSeconds,
    keyboardActivityCount,
    mouseActivityCount,
    clientKey,
  };
}

/* -------------------------------------------------------------------------- */
/* What crosses to the browser                                                */
/* -------------------------------------------------------------------------- */

/** One interval, as a screen sees it. No client key — it is a write-side detail. */
export interface ActivityIntervalCard {
  id: string;
  startedAt: string;
  endedAt: string;
  durationSeconds: number;
  keyboardActivityCount: number;
  mouseActivityCount: number;
  activityPercentage: number;
}

/** One shift, with the activity observed inside it. */
export interface TrackedSession {
  id: string;
  startedAt: string;
  /** Null while the shift is still open. */
  endedAt: string | null;
  /** Seconds of shift, clamped to the window being reported on. */
  trackedSeconds: number;
  /** Of those, the seconds covered by intervals that had input in them. */
  activeSeconds: number;
  /** Tracked minus active. Includes time no interval covered at all. */
  idleSeconds: number;
  /** Duration-weighted mean of the intervals in this shift, or null for none. */
  activityPercentage: number | null;
  /** How many screenshots were captured during it. */
  screenshotCount: number;
  /** True when an administrator has corrected this shift. */
  adjusted: boolean;
}

/**
 * One employee's row on the admin dashboard.
 *
 * `online` and `working` are two different facts and are both here because an
 * administrator asks two different questions. Online means a shift is open —
 * the portal says they are on the clock. Working means input has been observed
 * inside the idle threshold. Somebody reading a document is online and not
 * working, and that is a legitimate state, not an exception to report.
 */
export interface EmployeeTimeRow {
  userId: string;
  name: string;
  username: string;
  role: "ADMIN" | "AGENT";
  isActive: boolean;
  online: boolean;
  working: boolean;
  todaySeconds: number;
  weekSeconds: number;
  /** Duration-weighted mean over today, or null when nothing was observed. */
  activityPercentage: number | null;
  /** The newest interval end for this person, ever. Null if never tracked. */
  lastActivityAt: string | null;
  /** The open shift's start, or null. */
  currentSessionStartedAt: string | null;
  /**
   * Whether screenshots are actually arriving for the open shift, or null when
   * there is no open shift to judge.
   *
   * A third fact alongside `online` and `working`, and here for the same reason
   * they are both here: an administrator asks a different question. Online means
   * the portal says they are on the clock; working means input has been observed;
   * this means the workstation is demonstrably still photographing the screen.
   * Those can disagree, and the case where they do — clocked on, active, and no
   * screenshot for hours — is the one worth seeing, because it used to be
   * invisible. See `lib/captureHealthRules.ts`.
   */
  screenshotHealth: EmployeeScreenshotHealth | null;
}

/**
 * The screenshot verdict as the dashboard receives it.
 *
 * Flattened out of `CaptureHealthVerdict` rather than re-exported, so this file
 * stays the single description of the dashboard's payload and the rules module
 * stays free of presentation concerns.
 */
export interface EmployeeScreenshotHealth {
  state: "ok" | "warning" | "unhealthy" | "not-monitored";
  /** Minutes since the last screenshot arrived, or since the shift began. */
  gapMinutes: number;
  /** How many captures the server's cadence implies are missing. */
  missedIntervals: number;
  /** What the workstation said, when recent enough to be about now. A label only. */
  reason: string | null;
  /** True when the reason explains the gap without implying interference. */
  benign: boolean;
  /** The workstation claims capture is healthy and nothing has arrived. */
  contradicted: boolean;
  /** One line an administrator can act on. */
  summary: string;
}

/** The figures above the employee table. Every one is counted, never estimated. */
export interface TeamTimeSummary {
  totalEmployees: number;
  currentlyWorking: number;
  currentlyInactive: number;
  todaySeconds: number;
  weekSeconds: number;
  /** Duration-weighted mean across everyone today, or null. */
  averageActivityPercentage: number | null;
  /** The instant these were read, so a client clock can extend them honestly. */
  asOf: string;
}

/** The whole admin dashboard payload. */
export interface TeamTimePayload {
  summary: TeamTimeSummary;
  employees: EmployeeTimeRow[];
  policy: {
    intervalSeconds: number;
    idleThresholdSeconds: number;
    expectedEventsPerMinute: number;
  };
}

/** One row of the timesheet: one person, one day. */
export interface TimesheetRow {
  userId: string;
  name: string;
  /** `YYYY-MM-DD`, in the server's timezone. */
  day: string;
  /** The first shift start that day, or null when nothing was worked. */
  firstStartedAt: string | null;
  /** The last shift end that day. Null while a shift is still open. */
  lastEndedAt: string | null;
  trackedSeconds: number;
  activeSeconds: number;
  idleSeconds: number;
  activityPercentage: number | null;
  sessions: number;
}

/** One manual correction, as the audit list shows it. */
export interface TimeAdjustmentCard {
  id: string;
  createdAt: string;
  adminName: string;
  agentName: string;
  workSessionId: string;
  previousStartedAt: string;
  previousEndedAt: string | null;
  previousDurationSeconds: number | null;
  newStartedAt: string;
  newEndedAt: string | null;
  newDurationSeconds: number | null;
  reason: string;
}

/* -------------------------------------------------------------------------- */
/* The timesheet's range                                                      */
/* -------------------------------------------------------------------------- */

/**
 * The widest window a timesheet may be asked for, in days.
 *
 * A timesheet emits one row per employee per worked day, so its size is the
 * product of the range and the headcount — the only read in this feature that
 * is not one row per agent. A quarter is longer than any payroll period anybody
 * runs and keeps the worst case (roughly 92 × headcount) comfortably renderable.
 *
 * The preset ranges are all shorter than this; it exists for the custom picker,
 * where the natural mistake is a start date typed with the wrong year.
 */
export const MAX_TIMESHEET_DAYS = 92;

/**
 * The timesheet's period, from a query string.
 *
 * Built on `resolveRange`, so the presets, the day boundaries and the clamping
 * of a reversed custom pair are the same ones every other report in the portal
 * uses — the brief's daily / weekly / monthly / custom are its `today`,
 * `last7`, `last30` and `custom`. Anything unrecognised falls back to today,
 * exactly as it does there, because a report should not 400 an administrator
 * over a stale bookmark.
 *
 * The one thing added here is the ceiling: an over-long custom range is pulled
 * back to its last {@link MAX_TIMESHEET_DAYS} days rather than refused, so the
 * screen shows a period the reader can then correct instead of an error page.
 */
export function resolveTimesheetRange(
  params: URLSearchParams,
  today?: string,
): DateRange {
  const range = resolveRange(params.get("range"), params.get("from"), params.get("to"), today);
  if (range.days <= MAX_TIMESHEET_DAYS) return range;

  return resolveRange(
    "custom",
    addDays(range.toDay, -(MAX_TIMESHEET_DAYS - 1)),
    range.toDay,
    today,
  );
}

/* -------------------------------------------------------------------------- */
/* Formatting and small shared derivations                                    */
/* -------------------------------------------------------------------------- */

/**
 * The duration-weighted mean of a set of intervals.
 *
 * Weighted rather than a plain average of percentages, because the intervals in
 * a window are not all the same length once a client has merged two after a
 * hiccup — and an unweighted mean would let a 10-second interval count as much
 * as a 60-second one. `null` for an empty set rather than 0: "no activity was
 * observed" and "activity was observed and it was zero" are different facts,
 * and showing the first as 0% would report an agent who was never tracked as
 * having been idle all day.
 */
export function weightedActivity(
  intervals: readonly { durationSeconds: number; activityPercentage: number }[],
): number | null {
  let weighted = 0;
  let total = 0;

  for (const interval of intervals) {
    weighted += interval.activityPercentage * interval.durationSeconds;
    total += interval.durationSeconds;
  }

  return total === 0 ? null : Math.round(weighted / total);
}

/** `72` -> `72%`, `null` -> `—`. The one place the em dash is decided. */
export function formatActivity(value: number | null): string {
  return value === null ? "—" : `${value}%`;
}

/**
 * The band an activity figure falls in, for colouring a cell.
 *
 * Three bands and no more, with the thresholds named here so a screen cannot
 * invent its own. Deliberately not "good / bad": the labels are descriptive
 * because the figure is descriptive — see {@link activityPercentage}.
 */
export type ActivityBand = "none" | "low" | "moderate" | "high";

export function activityBand(value: number | null): ActivityBand {
  if (value === null) return "none";
  if (value < 25) return "low";
  if (value < 60) return "moderate";
  return "high";
}
