import { createReadStream } from "node:fs";
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";
import { Readable } from "node:stream";

import { DEMO_IMAGE_TYPES, type DemoImageType } from "./demoImageRules";

/**
 * Object storage for demo website images.
 *
 * Deliberately the same shape as `lib/screenshotStorage.ts` and
 * `lib/recordingStorage.ts`, which is the point of it existing at all rather
 * than being a fourth invention: a directory on the server, written and read
 * only by this process, addressed by an opaque key. Three file stores with
 * three different designs would be three sets of traversal rules to get right,
 * so this one follows the two that already exist — the root comes from an
 * environment variable, keys are generated here and never supplied, every path
 * is re-checked against the root, and writes are atomic.
 *
 * **Nothing serves this directory.** It is not under `public/`, nginx has no
 * location for it, and there is no route that maps a key to a URL. The one way
 * bytes leave it is `GET /api/demo-websites/:id/image`, which resolves the
 * caller from the session row in Postgres, refuses anyone without the Demo
 * Websites module, and looks the key up from the demo website row itself — the
 * key is never a parameter, so there is nothing for a caller to point anywhere.
 *
 * **The root must be outside the release tree.** Blue/green deploys replace the
 * release directory wholesale (deploy/README.md), so images stored inside it
 * would be destroyed by the next deploy and unrecoverable by a rollback.
 */

/**
 * Where demo images live.
 *
 * Development defaults to `.data/demo-images` in the project directory, which
 * `.gitignore` already covers via the `.data` rule — so a fresh clone needs no
 * configuration. That default is *inside* the project, which is exactly why
 * production must set `DEMO_IMAGES_DIR`; the same trade-off `SCREENSHOTS_DIR`
 * and `RECORDINGS_DIR` make, and the same warning in `.env.example`.
 */
export function demoImageRoot(): string {
  const configured = process.env.DEMO_IMAGES_DIR?.trim();
  return configured ? path.resolve(configured) : path.resolve(process.cwd(), ".data/demo-images");
}

/**
 * A cuid, or nothing.
 *
 * `demoWebsiteId` is the one part of a key that comes from outside this file.
 * It is always a cuid the server read from its own row lookup, never anything a
 * client sent — but a path segment built from a variable deserves an assertion
 * rather than an assumption, and the cost of being wrong here is a write
 * outside the storage root.
 */
function safeSegment(value: string): string {
  return /^[a-z0-9]{1,64}$/i.test(value) ? value : "unknown";
}

/**
 * A fresh key for a demo image.
 *
 * `YYYY/MM/<demo website id>/<epoch ms>-<16 random hex>.<ext>`.
 *
 * Sharded by month rather than by day, which is what recordings do and the
 * opposite of screenshots: the volumes are not comparable. A portal holds tens
 * of demo websites, each with at most one image that changes rarely, so a day
 * directory would mostly be an empty directory.
 *
 * The random suffix, not the timestamp, is what makes the name unguessable and
 * collision-proof. That matters more here than it does for a screenshot: an
 * image is *replaced* in place from the administrator's point of view, and a
 * predictable name would mean the new object could be written over the old one
 * before the row pointing at it had been updated.
 *
 * Nothing in the name comes from the client. There is no original filename
 * anywhere in this module — the browser's `file.name` is read by nobody.
 */
export function newDemoImageKey(
  contentType: DemoImageType,
  demoWebsiteId: string,
  now = new Date(),
): string {
  const extension = DEMO_IMAGE_TYPES[contentType].extension;
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  const unique = `${now.getTime()}-${randomBytes(16).toString("hex")}`;

  return `${year}/${month}/${safeSegment(demoWebsiteId)}/${unique}.${extension}`;
}

/**
 * Turn a key into an absolute path, refusing anything that escapes the root.
 *
 * Keys are generated by {@link newDemoImageKey} and stored in a unique column,
 * so in practice this cannot fail. It is checked on every read, write and
 * delete anyway, for the reason the two sibling stores give: "the value in that
 * column is always safe" is exactly the invariant a later feature quietly
 * breaks. It is also the last line of defence if a future endpoint is ever
 * careless enough to accept a key from a request — which none does today, and
 * which this check is here to survive.
 */
function resolveKey(key: string): string {
  const root = demoImageRoot();
  const resolved = path.resolve(root, key);
  const prefix = root.endsWith(path.sep) ? root : root + path.sep;
  if (!resolved.startsWith(prefix)) {
    throw new Error(`Refusing a storage key that escapes the demo image root: ${key}`);
  }
  return resolved;
}

/**
 * Write bytes and return the size actually stored.
 *
 * Written to a temporary name in the same directory and renamed into place, so
 * a crash or a full disk cannot leave a half-file at a key a database row is
 * about to point at: after a rename the key either exists complete or not at
 * all.
 */
export async function putDemoImage(key: string, bytes: Uint8Array): Promise<number> {
  const target = resolveKey(key);
  await mkdir(path.dirname(target), { recursive: true });

  const temporary = `${target}.${randomBytes(6).toString("hex")}.part`;
  try {
    await writeFile(temporary, bytes, { mode: 0o640 });
    await rename(temporary, target);
  } catch (error) {
    await rm(temporary, { force: true }).catch(() => {});
    throw error;
  }

  return bytes.byteLength;
}

/** Size on disk, or null when the object is missing. */
export async function demoImageSize(key: string): Promise<number | null> {
  try {
    const info = await stat(resolveKey(key));
    return info.isFile() ? info.size : null;
  } catch {
    return null;
  }
}

/**
 * An object as a web stream, ready to be a Response body.
 *
 * A stream rather than a `readFile`, for the reason the list screen makes
 * obvious: a page of a hundred rows with thumbnails is a hundred concurrent-ish
 * requests, and buffering each one whole would put a hundred images in the heap
 * to send bytes that are going straight out to a socket.
 *
 * No `Range` support. Ranges are what make an audio element seekable; an `<img>`
 * asks for a whole file and nothing else.
 */
export function demoImageStream(key: string): ReadableStream<Uint8Array> {
  return Readable.toWeb(createReadStream(resolveKey(key))) as ReadableStream<Uint8Array>;
}

/**
 * Delete an object. Missing is success — the caller's goal is "these bytes are
 * gone", and a delete that threw because a previous one succeeded would strand
 * the row it is cleaning up after.
 */
export async function deleteDemoImage(key: string): Promise<void> {
  await rm(resolveKey(key), { force: true });
}
