import { createReadStream } from "node:fs";
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";
import { Readable } from "node:stream";

/**
 * Object storage for call recordings.
 *
 * The portal had no file storage before this: the only upload — the CSV import
 * — is parsed straight into Postgres and the file itself is never kept. Audio
 * cannot work that way (25MB of bytea per meeting would ride along in every
 * backup and every careless `SELECT *`), so this is the storage layer, and it
 * is deliberately the smallest one that is actually production-ready: a
 * directory on the server, written and read only by this process.
 *
 * No S3, no bucket, no second set of credentials. The deployment is a single
 * VPS behind nginx (see deploy/README.md); adding an object store would mean a
 * new provider, new keys in `/etc/leadportal/env` and a second way to be
 * misconfigured, to solve a distribution problem this app does not have. The
 * seam is here if that changes: everything outside this file addresses audio by
 * an opaque `storageKey`, so swapping the body of these four functions for an
 * SDK call is the whole migration.
 *
 * Two properties this file is responsible for:
 *
 *   The root is outside the release tree. Blue/green deploys replace the
 *   release directory wholesale, so anything stored inside it is destroyed on
 *   the next deploy. `RECORDINGS_DIR` points at `/var/lib/leadportal/recordings`
 *   in production, and systemd is given write access to exactly that path.
 *
 *   Keys are generated here, never supplied. A storage key is
 *   `YYYY/MM/<32 random hex>.<ext>` where the extension comes from a fixed map,
 *   so no part of it is attacker-influenced. `resolveKey` re-checks that the
 *   resolved path is still under the root anyway — the cheap assertion that
 *   turns a future mistake into a 500 rather than a file read outside the root.
 */

/**
 * Where the audio lives.
 *
 * Development defaults to `.data/recordings` in the project directory, which
 * `.gitignore` covers, so a fresh clone needs no configuration to use the
 * feature. Production must set this: the default would land inside the release
 * directory and be deleted by the next deploy.
 */
export function storageRoot(): string {
  const configured = process.env.RECORDINGS_DIR?.trim();
  return configured ? path.resolve(configured) : path.resolve(process.cwd(), ".data/recordings");
}

/** Extension per accepted content type. The only source of the on-disk suffix. */
const EXTENSION_BY_TYPE: Record<string, string> = {
  "audio/mpeg": "mp3",
  "audio/wav": "wav",
  "audio/mp4": "m4a",
  "audio/webm": "webm",
  "audio/ogg": "ogg",
};

/**
 * A fresh key for a new object.
 *
 * 16 random bytes rather than the row's cuid: the key is minted before the row
 * exists (the bytes are written first, so a failed write never leaves a row
 * pointing at nothing), and an unguessable name means the storage directory
 * itself is not a listing of who called whom — a file leaked by a backup or a
 * stray `ls` is not addressable from the outside either way, since nothing
 * serves this directory but the authorized stream route.
 *
 * Sharded by year and month so the directory stays a workable size after a few
 * thousand calls, and so a retention sweep is a `rm -r` of one month.
 */
export function newStorageKey(contentType: string, now = new Date()): string {
  const extension = EXTENSION_BY_TYPE[contentType] ?? "bin";
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  return `${year}/${month}/${randomBytes(16).toString("hex")}.${extension}`;
}

/**
 * Turn a key into an absolute path, refusing anything that escapes the root.
 *
 * Keys are generated by `newStorageKey` and stored in a unique column, so in
 * practice this can only fail if something is very wrong. It is still checked
 * on every read and delete, because "the value in that column is always safe"
 * is exactly the kind of invariant that a later feature quietly breaks.
 */
function resolveKey(key: string): string {
  const root = storageRoot();
  const resolved = path.resolve(root, key);
  const prefix = root.endsWith(path.sep) ? root : root + path.sep;
  if (!resolved.startsWith(prefix)) {
    throw new Error(`Refusing a storage key that escapes the storage root: ${key}`);
  }
  return resolved;
}

/**
 * Write bytes and return the size actually stored.
 *
 * Written to a temporary name in the same directory and renamed into place, so
 * a crash or a full disk cannot leave a half-file at a key a database row is
 * about to point at: on a rename, the key either exists complete or not at all.
 */
export async function putRecording(key: string, bytes: Uint8Array): Promise<number> {
  const target = resolveKey(key);
  await mkdir(path.dirname(target), { recursive: true });

  const temporary = `${target}.${randomBytes(6).toString("hex")}.part`;
  try {
    await writeFile(temporary, bytes, { mode: 0o640 });
    await rename(temporary, target);
  } catch (error) {
    await rm(temporary, { force: true }).catch(() => {});
    throw error;
  }

  return bytes.byteLength;
}

/** Size on disk, or null when the object is missing. */
export async function recordingSize(key: string): Promise<number | null> {
  try {
    const info = await stat(resolveKey(key));
    return info.isFile() ? info.size : null;
  } catch {
    return null;
  }
}

/**
 * A byte range of an object, as a web stream ready to be a Response body.
 *
 * Ranges are what make an audio element seekable: the browser asks for the
 * last few kilobytes to find the duration, then for the region around wherever
 * the listener drags the scrubber. Reading the whole file and slicing it would
 * pull 25MB into memory to serve 8KB of it.
 */
export function recordingStream(
  key: string,
  range?: { start: number; end: number },
): ReadableStream<Uint8Array> {
  const nodeStream = createReadStream(resolveKey(key), range);
  // `Readable.toWeb` gives a stream the runtime can cancel — when the listener
  // seeks away mid-response the file handle is closed rather than left to be
  // read to the end into a socket nobody is listening on.
  return Readable.toWeb(nodeStream) as ReadableStream<Uint8Array>;
}

/**
 * Delete an object. Missing is success: the caller's goal is "these bytes are
 * gone", and a delete that throws because a previous delete already succeeded
 * would strand the database row it is supposed to be cleaning up after.
 */
export async function deleteRecording(key: string): Promise<void> {
  await rm(resolveKey(key), { force: true });
}
