import { createReadStream } from "node:fs";
import { mkdir, rename, rm, stat, writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import path from "node:path";
import { Readable } from "node:stream";

/**
 * Object storage for desktop screenshots.
 *
 * Deliberately the same shape as `lib/recordingStorage.ts`: a directory on the
 * server, written and read only by this process, addressed by an opaque key.
 * Two file stores with two different designs would be two sets of traversal
 * rules to get right, so this one follows the one that already exists — the
 * root comes from an environment variable, keys are generated here and never
 * supplied, every path is re-checked against the root, and writes are atomic.
 *
 * **Nothing serves this directory.** It is not under `public/`, nginx has no
 * location for it, and there is no route that maps a key to a URL. The one way
 * bytes leave it is `GET /api/screenshots/:id/image`, which resolves the caller
 * from the session row in Postgres, refuses anyone who is not an administrator,
 * and looks the key up from the screenshot row itself — the key is never a
 * parameter, so there is nothing for a caller to point anywhere.
 *
 * **The root must be outside the release tree.** Blue/green deploys replace the
 * release directory wholesale (deploy/README.md), so screenshots stored inside
 * it would be destroyed by the next deploy and unrecoverable by a rollback.
 */

/**
 * Where screenshots live.
 *
 * Development defaults to `.data/screenshots` in the project directory, which
 * `.gitignore` already covers — so a fresh clone needs no configuration. That
 * default is *inside* the project, which is exactly why production must set
 * `SCREENSHOTS_DIR`; the same trade-off `RECORDINGS_DIR` makes, and the same
 * warning in `.env.example`.
 */
export function storageRoot(): string {
  const configured = process.env.SCREENSHOTS_DIR?.trim();
  return configured ? path.resolve(configured) : path.resolve(process.cwd(), ".data/screenshots");
}

/** Extension per stored content type. The only source of the on-disk suffix. */
const EXTENSION_BY_TYPE: Record<string, string> = {
  "image/jpeg": "jpg",
};

/**
 * A cuid, or nothing.
 *
 * `userId` is the one part of a key that comes from outside this file. It is
 * always a cuid the server read from its own session lookup, never anything a
 * client sent — but a path segment built from a variable deserves an assertion
 * rather than an assumption, and the cost of being wrong here is a write
 * outside the storage root.
 */
function safeSegment(value: string): string {
  return /^[a-z0-9]{1,64}$/i.test(value) ? value : "unknown";
}

/**
 * A fresh key for a new screenshot.
 *
 * `YYYY/MM/DD/<user id>/<epoch ms>-<16 random hex>.jpg`.
 *
 * Sharded by day rather than by month (which is what recordings use), because
 * the volumes are not comparable: a few recordings a week against several
 * screenshots an hour per agent, all day. A day directory per agent stays
 * listable, and a retention sweep — a later stage — becomes `rm -r` of one
 * date.
 *
 * The random suffix, not the timestamp, is what makes the name collision-proof:
 * two captures in the same millisecond are possible and 16 bytes of CSPRNG are
 * not. The timestamp is there so a human can find a file by eye.
 *
 * Nothing in the name comes from the client. There is no original filename
 * anywhere in this module.
 */
export function newStorageKey(
  contentType: string,
  userId: string,
  now = new Date(),
): string {
  const extension = EXTENSION_BY_TYPE[contentType] ?? "bin";
  const year = now.getUTCFullYear();
  const month = String(now.getUTCMonth() + 1).padStart(2, "0");
  const day = String(now.getUTCDate()).padStart(2, "0");
  const unique = `${now.getTime()}-${randomBytes(16).toString("hex")}`;

  return `${year}/${month}/${day}/${safeSegment(userId)}/${unique}.${extension}`;
}

/**
 * Turn a key into an absolute path, refusing anything that escapes the root.
 *
 * Keys are generated by {@link newStorageKey} and stored in a unique column, so
 * in practice this cannot fail. It is checked on every read, write and delete
 * anyway, for the reason `recordingStorage` gives: "the value in that column is
 * always safe" is exactly the invariant a later feature quietly breaks.
 */
function resolveKey(key: string): string {
  const root = storageRoot();
  const resolved = path.resolve(root, key);
  const prefix = root.endsWith(path.sep) ? root : root + path.sep;
  if (!resolved.startsWith(prefix)) {
    throw new Error(`Refusing a storage key that escapes the storage root: ${key}`);
  }
  return resolved;
}

/**
 * Write bytes and return the size actually stored.
 *
 * Written to a temporary name in the same directory and renamed into place, so
 * a crash or a full disk cannot leave a half-file at a key a database row is
 * about to point at: after a rename the key either exists complete or not at
 * all.
 */
export async function putScreenshot(key: string, bytes: Uint8Array): Promise<number> {
  const target = resolveKey(key);
  await mkdir(path.dirname(target), { recursive: true });

  const temporary = `${target}.${randomBytes(6).toString("hex")}.part`;
  try {
    await writeFile(temporary, bytes, { mode: 0o640 });
    await rename(temporary, target);
  } catch (error) {
    await rm(temporary, { force: true }).catch(() => {});
    throw error;
  }

  return bytes.byteLength;
}

/** Size on disk, or null when the object is missing. */
export async function screenshotSize(key: string): Promise<number | null> {
  try {
    const info = await stat(resolveKey(key));
    return info.isFile() ? info.size : null;
  } catch {
    return null;
  }
}

/**
 * An object as a web stream, ready to be a Response body.
 *
 * A stream rather than a `readFile`, for the reason the gallery makes obvious:
 * a page of fifty screenshots is fifty concurrent-ish requests, and buffering
 * each one whole would put fifty images in the heap at once to send bytes that
 * are going straight out to a socket. `Readable.toWeb` also gives the runtime a
 * stream it can cancel, so an administrator who closes the tab mid-response
 * releases the file handle instead of having it read to the end into nothing.
 *
 * No `Range` support, unlike `recordingStream`. Ranges are what make an audio
 * element seekable; an `<img>` asks for a whole file and nothing else, so the
 * parsing that seeking needs would be code with no caller.
 *
 * The key is re-checked against the root by {@link resolveKey} like every other
 * path in this file — a missing file throws on read, which the caller answers
 * as a 404 rather than a stack trace.
 */
export function screenshotStream(key: string): ReadableStream<Uint8Array> {
  return Readable.toWeb(createReadStream(resolveKey(key))) as ReadableStream<Uint8Array>;
}

/**
 * Delete an object. Missing is success — the caller's goal is "these bytes are
 * gone", and a delete that threw because a previous one succeeded would strand
 * the row it is cleaning up after.
 */
export async function deleteScreenshot(key: string): Promise<void> {
  await rm(resolveKey(key), { force: true });
}
