import type { SessionUser } from "./access";
import { prisma } from "./prisma";
import {
  normaliseDisplayId,
  resolveCapturedAt,
  ScreenshotError,
  validateScreenshot,
} from "./screenshotRules";
import { deleteScreenshot, newStorageKey, putScreenshot } from "./screenshotStorage";
import { getActiveWorkSession } from "./workSessions";

/**
 * Storing a screenshot: the bytes, then the row.
 *
 * ---------------------------------------------------------------------------
 * What the client is allowed to decide
 * ---------------------------------------------------------------------------
 * Almost nothing, and that is the point of this file.
 *
 *   the image bytes        yes — validated and sniffed before anything is kept
 *   `capturedAt`           advisory; clamped to the server's clock
 *   `displayId`            an opaque label, stored and never acted on
 *   ------------------------------------------------------------------------
 *   `userId`               **no** — taken from the authenticated device
 *   `workSessionId`        **no** — looked up here, from the portal's own view
 *   width / height         **no** — read out of the JPEG itself
 *   the filename / path    **no** — generated by `newStorageKey`
 *   the stored format      **no** — sniffed from the magic bytes
 *
 * There is no field in an upload that says who it belongs to, so an agent
 * cannot file a screenshot against another account or another shift. This is
 * not a check that could be forgotten — the information simply is not taken
 * from the request.
 *
 * ---------------------------------------------------------------------------
 * No active shift, no screenshot
 * ---------------------------------------------------------------------------
 * The work session is resolved by {@link getActiveWorkSession}, which is the
 * portal's own read and returns null for a shift whose heartbeat has stopped.
 * So "the agent is working" is decided by the portal on the server, at the
 * moment of upload — not by the desktop client, whose view of it is a poll that
 * can be up to a minute stale, and not by anything in the request body.
 *
 * This read is the only thing here that touches work sessions, and it writes
 * nothing: uploading a screenshot cannot open, extend or close a shift.
 *
 * ---------------------------------------------------------------------------
 * Bytes first, row second
 * ---------------------------------------------------------------------------
 * The file is written before the row, and the file is deleted if the row fails.
 * The other order would leave a row pointing at nothing on a disk error, which
 * is a broken screenshot in a viewer; this order can at worst leave an orphaned
 * file, which costs disk and is invisible. A later retention sweep can find
 * orphans by their absence from the table; nothing can recover a lost image.
 */

export interface StoredScreenshot {
  id: string;
  capturedAt: string;
  width: number;
  height: number;
  fileSize: number;
  format: string;
}

export async function saveScreenshot(params: {
  /** The authenticated agent, from the monitor device. Never from the body. */
  user: SessionUser;
  /** Which workstation uploaded it, for the audit trail. */
  deviceId: string | null;
  bytes: Uint8Array;
  /** Client-reported; clamped. */
  capturedAtRaw: unknown;
  /** Client-reported; an opaque label. */
  displayIdRaw: unknown;
}): Promise<StoredScreenshot> {
  const { user, bytes } = params;

  // Refused before the image is even looked at: an agent who is not on the
  // clock has no shift to attribute a screenshot to, and the row's
  // `workSessionId` is not nullable precisely so this cannot be skipped.
  const active = await getActiveWorkSession(user.id);
  if (!active) {
    throw new ScreenshotError(
      "no_active_work_session",
      "No active work session. Screenshots are only accepted while you are on the clock.",
      409,
    );
  }

  // Format, integrity and the true dimensions, from the bytes themselves.
  const facts = validateScreenshot(bytes);

  const capturedAt = resolveCapturedAt(params.capturedAtRaw);
  const displayId = normaliseDisplayId(params.displayIdRaw);

  const storageKey = newStorageKey(facts.type, user.id);
  const fileSize = await putScreenshot(storageKey, bytes);

  try {
    const row = await prisma.screenshot.create({
      data: {
        userId: user.id,
        workSessionId: active.id,
        deviceId: params.deviceId,
        capturedAt,
        storageKey,
        width: facts.width,
        height: facts.height,
        fileSize,
        format: facts.type,
        displayId,
      },
      select: { id: true, capturedAt: true },
    });

    return {
      id: row.id,
      capturedAt: row.capturedAt.toISOString(),
      width: facts.width,
      height: facts.height,
      fileSize,
      format: facts.type,
    };
  } catch (error) {
    // The row is what makes the file findable. Without one the bytes are
    // unreachable by anything in the application, so they are removed rather
    // than left to accumulate as garbage nobody knows how to attribute.
    await deleteScreenshot(storageKey).catch(() => {});
    throw error;
  }
}
